---
- name: install web packages
  pacman: name={{ item }} state=latest
  with_items:
    - nginx-mainline

- name: nginx logs directory
  file:
    state: directory
    path: /var/log/nginx
    owner: http
    group: http
  notify: reload nginx

- name: nginx config directory
  file:
    state: directory
    path: /etc/nginx/conf.d
  notify: reload nginx

- name: nginx default configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: reload nginx

- name: start and enable nginx
  service:
    name: nginx
    enabled: true
    state: started