---
- name: install postgres packages
  pacman:
    name: '{{ item }}'
    state: latest
  with_items:
    - postgresql
    - python-psycopg2

- name: stat db
  stat:
    path: /var/lib/postgres/data/postgresql.conf
  register: postgrescreated

- name: init db
  shell: initdb --locale en_US.UTF-8 -E UTF8 -D '/var/lib/postgres/data'
  become: yes
  become_user: postgres
  when: postgrescreated.stat.exists == False

- name: pg_hba config file
  template:
    src: pg_hba.conf.j2
    dest: /var/lib/postgres/data/pg_hba.conf
    owner: postgres
    group: postgres

- name: postgresql config file
  template:
    src: postgresql.conf.j2
    dest: /var/lib/postgres/data/postgresql.conf
    owner: postgres
    group: postgres

- name: enable and start postgres
  service:
    name: postgresql
    state: running
    enabled: true

- name: create databases
  postgresql_db:
    name: '{{ item }}'
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
  with_items: '{{ postgres.dbs }}'

- name: create users
  postgresql_user:
    db: '{{ item.name }}'
    name: '{{ item.name }}'
    password: '{{ item.password }}'
    priv: ALL
  with_items: '{{ postgres.users }}'